import { useState } from "react";
import { ArrowSquareOut } from "@phosphor-icons/react";
import report from "../../data/report.json";

const defaults = { postalCode: "", driverAge: 35, annualMileageMil: 1500, downPaymentPercent: 20, loanRatePercent: report.parameters.loanRatePercent, fuelPriceSekPerLitre: report.parameters.fuelPriceSekPerLitre.Bensin, insuranceLevel: "hel" };

function CalcSettings() {
  const [settings, setSettings] = useState(() => { try { return { ...defaults, ...JSON.parse(localStorage.getItem("bilradarn-settings") || "{}") }; } catch { return defaults; } });
  const update = (key, value) => setSettings((current) => ({ ...current, [key]: value }));
  const save = () => { localStorage.setItem("bilradarn-settings", JSON.stringify(settings)); window.dispatchEvent(new Event("bilradarn-settings-changed")); };
  return <section className="info-table calc-settings"><h2>Personliga kalkylinställningar</h2><p>Ändringar räknas inte om förrän du trycker på Spara.</p><div className="settings-grid"><label>Postnummer<input value={settings.postalCode} onChange={e => update("postalCode", e.target.value)} placeholder="411 10" /></label><label>Förarens ålder<input type="number" min="18" max="99" value={settings.driverAge} onChange={e => update("driverAge", Number(e.target.value))} /></label><label>Körsträcka (mil/år)<input type="number" min="500" step="100" value={settings.annualMileageMil} onChange={e => update("annualMileageMil", Number(e.target.value))} /></label><label>Kontantinsats (%)<input type="number" min="0" max="80" step="5" value={settings.downPaymentPercent} onChange={e => update("downPaymentPercent", Number(e.target.value))} /></label><label>Billåneränta (%)<input type="number" min="0" step="0.1" value={settings.loanRatePercent} onChange={e => update("loanRatePercent", Number(e.target.value))} /></label><label>Bensinpris (kr/l)<input type="number" min="0" step="0.1" value={settings.fuelPriceSekPerLitre} onChange={e => update("fuelPriceSekPerLitre", Number(e.target.value))} /></label><label>Försäkringsnivå<select value={settings.insuranceLevel} onChange={e => update("insuranceLevel", e.target.value)}><option value="halv">Halv</option><option value="hel">Hel</option><option value="stor">Utökat</option></select></label></div><button className="primary-action" onClick={save}>Spara inställningar</button><small>Grundrankningen ändras inte; personliga scenarier beräknas separat.</small></section>;
}

export function Info() {
  const steps = [["Hitta erbjudanden","Waykes aktuella handlarannonser filtreras på Göteborg +150 km och familjekaross."],["Läs hela säljsidan","Pris, identitet, skatt, WLTP, utrustning, handlare och bilder hämtas från detaljsidan."],["Kontrollera kraven","Utrustning märks som bekräftad eller ej verifierad utan att kamera, ISOFIX eller antisladd blockerar."],["Räkna 36 månader","Värdeminskning, lån, bränsle, skatt, försäkring, service, däck och reparationer summeras."],["Visa osäkerhet","Verifierade belopp, modellberäkningar och estimat märks separat."],["Uppdatera och jämför","Två dagliga körningar hämtar om källorna och rapporterar ändringar."]];
  return <><header className="page-heading"><div><span className="eyebrow">METOD OCH DATA</span><h1>Så blir en annons en ekonomisk plan</h1><p>Rapporten skiljer på observerade fakta och sådant som fortfarande måste uppskattas.</p></div></header><div className="info-grid">{steps.map(([title,text], i) => <section key={title}><strong>{i + 1}</strong><h2>{title}</h2><p>{text}</p></section>)}</div><CalcSettings/><section className="info-table"><h2>Källor för gemensamma antaganden</h2>{report.sources.map(s => <article key={s.url}><div><strong>{s.label}</strong><p>{s.note}</p></div><a href={s.url} target="_blank" rel="noreferrer"><ArrowSquareOut /></a></article>)}</section></>;
}
