import { Bell, Car, MapPin, Scales } from "@phosphor-icons/react";
import { money } from "../../ui/formatters";
import liveReport from "../../data/report.json";
import { resolveTravelDistance, travelDistanceBand } from "./travelDistance";

function OfferCard({ offer, selected, toggle, openOffer }) {
  const exception = offer.quality?.selection?.lane === "exception";
  const researchPending = offer.enrichment?.status === "pending-reliability";
  const label = offer.kind === "buy" ? ["KÖP", exception && "MJUKT UNDANTAG", researchPending && "RESEARCH VÄNTAR"].filter(Boolean).join(" · ") : "PRIVATLEASING";
  const travelDistance = resolveTravelDistance(offer);
  const distanceBand = travelDistanceBand(travelDistance);
  return <article className={`live-offer ${selected ? "selected" : ""}`}><div className="rank-number">{offer.rank}</div><button className="offer-link" onClick={() => openOffer(offer.id)}><div className="offer-image">{offer.imageUrls?.[0] ? <img src={offer.imageUrls[0]} alt={offer.title} /> : <Car />}</div><div className="offer-copy"><span className="kind-label">{label}</span><strong>{offer.title}</strong><small>{offer.variant}</small><span className="offer-location"><MapPin weight="fill" />{offer.place || offer.dealer}{travelDistance ? ` · ${travelDistance.approximate ? "ca " : ""}${travelDistance.km} km` : ""}{distanceBand && <b className={`travel-badge ${distanceBand.className}`} title={`${distanceBand.description}${travelDistance?.approximate ? " (ungefärligt köravstånd)" : ""}`}><MapPin weight="fill" />{distanceBand.label}</b>}</span><em>{offer.kind === "buy" ? `${offer.modelYear} · ${new Intl.NumberFormat("sv-SE").format(offer.mileageMil)} mil` : "36 månader · 1 500 mil/år"}</em></div></button><div className="offer-cost"><span>Ekonomisk kostnad, 36 mån</span><strong>{money(offer.economics.total36Sek)}</strong><b>{money(offer.economics.monthlyEconomicSek)}/mån</b><small>Stress {money(offer.economics.stressTotal36Sek)}</small></div><button className="compare-check" onClick={() => toggle(offer.id)}>{selected ? "Vald" : "+ Jämför"}</button></article>;
}

export function Ranking({ report = liveReport, selected, toggle, openOffer, setPage, query }) {
  const match = (offer) => `${offer.title} ${offer.variant} ${offer.dealer}`.toLowerCase().includes(query.toLowerCase());
  return <><header className="page-heading"><div><span className="eyebrow">AKTUELLA ERBJUDANDEN</span><h1>Familjebilar med hela ekonomin synlig</h1><p>Separata listor för köp och leasing. Endast levande källor – inga exempelfordon.</p></div><button className="primary-action" onClick={() => setPage("compare")}><Scales />Jämför valda ({selected.length})</button></header><div className="filter-strip"><span>Göteborg +150 km prioriteras</span><span className="distance-key near-10"><MapPin weight="fill" />≤10 mil</span><span className="distance-key near-15"><MapPin weight="fill" />10–15 mil</span><span>Automat normalfall</span><span>Bensin/diesel/ej laddbar hybrid</span><span>2021–2023 normalt · 2020/2024 undantag</span><span>Högst 250 tkr</span><span>Högst 7 500 mil normalt · 10 000 undantag</span></div>{report.changes.length > 0 && <div className="change-banner"><Bell weight="fill" /><div><strong>{report.changes.length} förändringar i senaste kontrollen</strong><span>Nya, borttagna eller prisändrade annonser upptäcktes.</span></div></div>}<div className="ranking-grid"><section className="ranking-panel"><div className="panel-title"><div><span>PRIVATLEASING</span><h2>Aktuella tillverkarerbjudanden</h2></div><p>36 mån · 1 500 mil/år</p></div>{report.leases.filter(match).map((offer) => <OfferCard key={offer.id} offer={offer} selected={selected.includes(offer.id)} toggle={toggle} openOffer={openOffer} />)}</section><section className="ranking-panel"><div className="panel-title"><div><span>KÖP HOS HANDLARE</span><h2>Filtrerade liveannonser</h2></div><p>Riskjusterad treårskostnad</p></div>{report.purchases.filter(match).map((offer) => <OfferCard key={offer.id} offer={offer} selected={selected.includes(offer.id)} toggle={toggle} openOffer={openOffer} />)}</section></div></>;
}
